gophermart-1
ZhuzhomaAL/GopherMart pull request #1
Opened 2023-08-25 08:48 UTC by ZhuzhomaAL

2023-08-25 18:46 UTC, valentinsoe requested changes
Спасибо за работу!
Классно, что код разделен на множество мелких модулей, что есть отдельно хендлеры, отдельно бизнес-логика и отдельно хранилище.

Мне правда не очень понятно что значат adapter и core.
Я бы чуть снизил степень вложенности. В одну папку бы положил хендлеры и роутеры, в одну мидлвары, в третью всю работу с БД, в четвертую модели и т.д.

Я понимаю, что работа не закончена, но предупрежу сразу:
Запрашивать статусы заказа надо многопоточно
Если ты используешь каналы(создавая "заявки" на обработку), то учти что рестарт приложения приведет к тому, что все содержимое каналов исчезнет.
Также учти, что буфер каналов не может быть бесконечным. И если хендлер создания заказ пишет в канал у которого занят буфер - хендлер повиснет сколь угодно надолго.
Хотя мы в базе заказ уже зафиксировали и можем ответить пользователю не дожидаясь этого.

2023-08-25 18:46 UTC, valentinsoe commented on internal/app/adapter/handlers/event/fetch.go
> +package event
Не знаю куда именно написать - но я не понимаю смысл слова adapter в данном контексте:) 
Почему в нем лежат роутер и хендлеры?

2023-08-25 18:46 UTC, valentinsoe commented on internal/app/adapter/clients/loyal/client.go
> +type LoyaltyClient struct {
Я бы сделал еще шаг и добавил интерфейс. Позволить проще подменять реализацию в тестах.

2023-08-25 18:46 UTC, valentinsoe commented on cmd/gophermart/main.go
> +	ordersChannel := make(chan string, 0)
Я пока не прочитал как именно эти каналы будут использоваться, но кажется 0-вая длина буффера нам не нужна.

2023-08-25 18:46 UTC, valentinsoe commented on internal/app/adapter/handlers/http/balance.go
> +	userID, ok := r.Context().Value(auth.ContextUserID).(uuid.UUID)
У нас много таких вызовов. Я бы рекомендовал оформить это в функцию. Будет лучше читаться

2023-08-25 18:46 UTC, valentinsoe commented on internal/app/adapter/handlers/event/fetch.go
> +	lf        service.NewOrderProcessor
NewOrderProcessor по имени lf меня смущает:)

2023-08-25 18:46 UTC, valentinsoe commented on internal/app/adapter/handlers/event/fetch.go
> +		case o, ok := <-*f.ochan:
Лучше поменять кейсы местами. Они проверяются по порядку. И если в канале всегда будет что читать - массив лопнет:)

2023-08-25 18:46 UTC, valentinsoe commented on internal/app/adapter/handlers/event/fetch.go
> +				err := f.lf.ProcessNewOrder(context.Background(), o)
Мы создаем очень много контекстов. Это лишняя нагрузка, которая нам не полезна.

2023-08-25 18:46 UTC, valentinsoe commented on internal/app/adapter/handlers/event/fetch.go
> +func NewFetchHandler(ochan *chan string, lf service.NewOrderProcessor, frequency time.Duration) *FetchHandler {
Каналы лучше передавать по значению.

2023-08-25 18:46 UTC, valentinsoe commented on internal/app/service/order.go
> +	*os.ochan <- number
Если буффер канала будет занят, то хендлер повиснет. Потенциально очень надолго.

2023-08-25 18:46 UTC, valentinsoe commented on internal/app/service/order.go
> +	if err := os.orderRepo.ButchUpdateOrdersAndBalance(ctx, orders, transactions); err != nil {
Butch -> Batch

2023-08-31 07:08 UTC, ZhuzhomaAL commented on internal/app/adapter/handlers/event/fetch.go
> +package event
Я пользовалась вот этой статьей https://www.golinuxcloud.com/hexagonal-architectural-golang/. По моей задумке, в adapter лежат методы для взаимодействия с "внешним миром" (запросы к сервису лояльности, хендлеры, запросы к бд). В core лежат основные сущности сервиса(структуры, ошибки, интерфейсы, включая интерфейсы для адаптеров и для бизнес логики(service см.далее)). В infra лежат вспомогательные методы(авторизация, конфиг). В service лежат методы бизнес логики

2023-08-31 07:11 UTC, ZhuzhomaAL commented on internal/app/adapter/clients/loyal/client.go
> +type LoyaltyClient struct {
Тут не очень поняла. Для клиента уже есть интерфейс

2023-08-31 07:11 UTC, ZhuzhomaAL commented on cmd/gophermart/main.go
> +	ordersChannel := make(chan string, 0)
Поменяла на 1000

2023-08-31 07:14 UTC, ZhuzhomaAL commented on internal/app/adapter/handlers/event/fetch.go
> +				err := f.lf.ProcessNewOrder(context.Background(), o)
вынесла в main

2023-08-31 07:15 UTC, ZhuzhomaAL commented on internal/app/service/order.go
> +	*os.ochan <- number
сделала запись номера в канал в новом потоке

2023-08-31 14:45 UTC, valentinsoe commented on internal/app/adapter/handlers/event/fetch.go
> +package event
Ок. Честно не являюсь ценителем такой схемы, но это вкусовщина. Можно не обращать внимание

2023-08-31 14:48 UTC, valentinsoe commented on cmd/gophermart/main.go
> +	fetchHandler := event.NewFetchHandler(ordersChannel, orderProcessor, time.Second, 20, l)
time..Second и тем более 20 - примеры magicNumbers. Не посмотрев описания метода, я не пойму что они значат. Лучше под это заводить переменные/константы у которых есть значащие имена.

2023-08-31 14:49 UTC, valentinsoe commented on internal/app/adapter/clients/loyal/client.go
> +type LoyaltyClient struct {
Ок, просто ожидал увидеть его в этом пакете:) Действительно есть.

2023-08-31 15:42 UTC, valentinsoe requested changes
Спасибо за работу.

В целом очень хорошо и аккуратно распределена ответственность по пакетам. Но есть ряд нюансов, часть из них описаны в комментариях, часть допишу тут:

1) нет тестов
2) перезагрузка сервера приведет к тому, что заказы, по которым мы не получили финальный статус повиснут навсегда
3) если во внешней системе повиснет 1000(размер канала) заказов в статусе PROCESSING, наш сервис не то чтобы повиснет.... но будет работать странно
4) я не вижу пользы от разделения заказа на две сущности(заказ+транзакция).
5) если писать в каналы не только номер заказа, но и его ID, то batch-обновление заказа будет сильно проще и эффективней реализовано.

2023-08-31 15:42 UTC, valentinsoe commented on internal/app/adapter/clients/loyal/client.go
> +				return response.StatusCode() == http.StatusTooManyRequests
Это не лучший подход к обработке кода 429.
Во-первых у нас есть в ответе информация о том, сколько нам ждать. Во-вторых это не остановит другие горутины от "бомбардировки" сервера запросами.

2023-08-31 15:42 UTC, valentinsoe commented on internal/app/adapter/clients/loyal/client.go
> +	orderInfo := new(clients.OrderLoyaltyInfo)
Мне кажется проще однажды в SetResult передать его как &orderInfo, чем в 4 местах возвращать как *orderInfo :)

2023-08-31 15:42 UTC, valentinsoe commented on internal/app/adapter/handlers/event/fetch.go
> +				break Loop
Можно убрать метку Loop, она здесь не требуется.

2023-08-31 15:42 UTC, valentinsoe commented on internal/app/adapter/handlers/event/fetch.go
> +				orderNumber := o
А почему просто не использовать дальше o?

2023-08-31 15:42 UTC, valentinsoe commented on internal/app/adapter/handlers/event/update.go
> +				break Loop
Тоже лишняя метка

2023-08-31 15:42 UTC, valentinsoe commented on internal/app/adapter/handlers/http/balance.go
> +	current, err := b.bs.GetUserBalance(r.Context(), userID)
При таком разделении на уровни - кажется логика двух вызовов к БД(она же бизнес-логика) должна быть не в хендлерах, а в сервисе.

2023-08-31 15:42 UTC, valentinsoe commented on internal/app/adapter/handlers/http/balance.go
> +			http.Error(w, "request is empty, expected not empty", http.StatusBadRequest)
А если нам вместо JSON в боди прислали картинку, это уже не будет BadRequest, а станет InternalServerError?

2023-08-31 15:42 UTC, valentinsoe commented on internal/app/adapter/handlers/http/order.go
> +		if errors.As(err, &errInvalidFormat) {
Тут достаточно Is, вместо As и можно не создавать лишнюю переменную.

2023-08-31 15:42 UTC, valentinsoe commented on internal/app/adapter/handlers/http/order.go
> +	w.Header().Set("Content-Type", "application/json")
Лучше перенести ближе к концу функции. Ведь если мы делаем http.Error с текстом, то в боди будет не JSON

2023-08-31 15:42 UTC, valentinsoe commented on internal/app/adapter/handlers/http/router.go
> +	r.Use(middleware.Timeout(100 * time.Second))
В задании упоминается еще сжатие запросов.

2023-08-31 15:42 UTC, valentinsoe commented on internal/app/adapter/repository/postgres/transaction.go
> +func (tr TransactionRepository) GetWithdrawSumByUser(ctx context.Context, userID uuid.UUID) (float64, error) {
Не помню занудствовал ли я уже в твоей работе, но Withdraw - глагол. Существительное - withdrawal

2023-08-31 15:42 UTC, valentinsoe commented on internal/app/core/domain/user/user.go
> +func (u User) CheckPassword(password string) bool {
Этой и следующей функции место скорее в инфре, чем вместе с описанием доменной модели.

2023-08-31 15:42 UTC, valentinsoe commented on internal/app/infra/auth/auth.go
> +const ContextUserID contextUserIDKey = iota
Уже не у первого студента вижу такой подход к ключу в контексте. И даже уже получал ответ, что им так сказал их предыдущий ментор.
Но я не вижу логику в использовании мало-уникального значения 0, вместо понятного строкового "userID"

2023-08-31 15:42 UTC, valentinsoe commented on internal/app/service/balance.go
> +	return bs.repo.CreateTransaction(
Так как эта операция и получение баланса выполняются в разных транзакция(в смысле СУБД транзакциях) - то можно увести баланс в отрицательный при одновременных запросах на списание.

2023-08-31 15:42 UTC, valentinsoe commented on internal/app/service/order.go
> +	if err := os.orderRepo.CreateOrder(
Аналогично, проверка наличия и создание должны выполняться в одной транзакции, иначе пользователь может получить 500 вместо 200 или 409

2023-08-31 15:42 UTC, valentinsoe commented on internal/app/service/order.go
> +		os.ordersChannel <- number
Если у нас забьется буффер канала и будет поступать много новых - то в памяти будет висеть потенциально неограниченно большое количество горутин.

2023-08-31 15:42 UTC, valentinsoe commented on internal/app/service/order.go
> +	return os.orderRepo.DeleteOrder(ctx, o)
Тоже нужно делать в одной транзакции. Или лучше не получать его заранее, а посмотреть сколько строк удалилось.

2023-08-31 15:42 UTC, valentinsoe commented on internal/app/service/order.go
> +		o, err := os.orderRepo.GetByNumber(ctx, i.Order)
Если не разделять сущность заказа и транзакции за его начисления, то не придется тут так сложно писать:)
Где мы в случае 1000 заказов - сформируем тысячу запросов на получение заказов, чтобы из них сформировать транзакции

2023-08-31 15:42 UTC, valentinsoe commented on internal/app/service/order.go
> +	ctx context.Context, info []clients.OrderLoyaltyInfo, orders *[]order.Order, transactions *[]transaction.Transaction,
orders и transactions - выходные параметры.

2023-08-31 15:42 UTC, valentinsoe commented on internal/app/service/order.go
> +	errors = append(errors, os.fillInfo(ctx, info, &orders, &transactions)...)
А почему бы просто не присвоить? Зачем делать slice = append(anotherSlice....) ?

2023-08-31 15:42 UTC, valentinsoe commented on internal/app/service/order_processor.go
> +			_ = op.os.RemoveOrder(ctx, number)
Лучше помечать его как невалидный. А то пользователь удивится, что он заказ загрузил, а после он просто безвозвратно пропал.

2023-09-06 15:51 UTC, ZhuzhomaAL commented on internal/app/adapter/clients/loyal/client.go
> +				return response.StatusCode() == http.StatusTooManyRequests
Добавила отмену контекста и sleep

2023-09-06 15:54 UTC, ZhuzhomaAL commented on internal/app/adapter/handlers/event/fetch.go
> +				orderNumber := o
Может быть неожиданный результат при запуске горутин внутри цикла, если не записать значение в отдельную переменную.

2023-09-06 15:55 UTC, ZhuzhomaAL commented on internal/app/adapter/handlers/http/balance.go
> +	current, err := b.bs.GetUserBalance(r.Context(), userID)
Мне кажется, что объединение двух разных значений в ответ - это логика сборки ответа и она должна быть в хендлере.

2023-09-06 15:57 UTC, ZhuzhomaAL commented on internal/app/adapter/handlers/http/order.go
> +		if errors.As(err, &errInvalidFormat) {
У меня не получилось использовать Is не создавая лишнюю переменную, поэтому оставила так. Возможно, потому что в ошибке есть поле с номером заказа.

2023-09-06 16:03 UTC, ZhuzhomaAL commented on internal/app/service/order.go
> +		o, err := os.orderRepo.GetByNumber(ctx, i.Order)
Всё равно нужно получать заказы, чтобы проверить изменился ли статус, чтобы не обновлять лишний раз. Переделала на один запрос вместо запросов в цикле.

2023-09-07 05:39 UTC, valentinsoe approved these changes
Спасибо за исправления!

Из того, что хотел еще добавить - называть какую-то сущность в проекте transactions, если в проекте есть работа с БД не стоит:)
Пугаюсь, когда вижу, что функция возвращает массив транзакций.

2023-09-07 05:39 UTC, valentinsoe commented on internal/app/adapter/handlers/event/fetch.go
> +				orderNumber := o
Но проще будет выглядеть, если сделать go f.processOneOrder(o). И код будет проще читаться и с замыканием бороться не придется

2023-09-07 05:39 UTC, valentinsoe commented on internal/app/adapter/handlers/event/fetch.go
> +							cancelRequests()
Тут мы можем отменить запросы, на которые уже получили ответ от внешнего сервиса, но еще не успели записать к нам в БД

2023-09-07 05:39 UTC, valentinsoe commented on internal/app/adapter/handlers/http/order.go
> +		if errors.As(err, &errInvalidFormat) {
Да, не посмотрел, что у тебя еще поле есть. Is работать не будет.

2024-04-04 13:26 UTC, merged